import type { TarotCard } from "../tarot/shared/types.js";

export const MAJOR_ARCANA = [
  ["fool", "The Fool"],
  ["magician", "The Magician"],
  ["high_priestess", "The High Priestess"],
  ["empress", "The Empress"],
  ["emperor", "The Emperor"],
  ["hierophant", "The Hierophant"],
  ["lovers", "The Lovers"],
  ["chariot", "The Chariot"],
  ["strength", "Strength"],
  ["hermit", "The Hermit"],
  ["wheel_of_fortune", "Wheel of Fortune"],
  ["justice", "Justice"],
  ["hanged_man", "The Hanged Man"],
  ["death", "Death"],
  ["temperance", "Temperance"],
  ["devil", "The Devil"],
  ["tower", "The Tower"],
  ["star", "The Star"],
  ["moon", "The Moon"],
  ["sun", "The Sun"],
  ["judgement", "Judgement"],
  ["world", "The World"],
] as const;

const MINOR_RANKS = [
  ["ace", "Ace", 1],
  ["two", "Two", 2],
  ["three", "Three", 3],
  ["four", "Four", 4],
  ["five", "Five", 5],
  ["six", "Six", 6],
  ["seven", "Seven", 7],
  ["eight", "Eight", 8],
  ["nine", "Nine", 9],
  ["ten", "Ten", 10],
  ["page", "Page", 11],
  ["knight", "Knight", 12],
  ["queen", "Queen", 13],
  ["king", "King", 14],
] as const;

const SUITS = [
  ["wands", "Wands", "fire"],
  ["cups", "Cups", "water"],
  ["swords", "Swords", "air"],
  ["pentacles", "Pentacles", "earth"],
] as const;

export const CANONICAL_CARD_MANIFEST: Array<
  Pick<TarotCard, "id" | "name" | "arcana" | "suit" | "number">
> = [
  ...MAJOR_ARCANA.map(([id, name], number) => ({
    id,
    name,
    arcana: "major" as const,
    number,
  })),
  ...SUITS.flatMap(([suit, suitName]) =>
    MINOR_RANKS.map(([rankId, rankName, number]) => ({
      id: `${rankId}_of_${suit}`,
      name: `${rankName} of ${suitName}`,
      arcana: "minor" as const,
      suit,
      number,
    })),
  ),
];

export const MODERN_RWS_CARD_ANCHORS: Record<
  string,
  { upright: string[]; reversed: string[] }
> = {
  fool: { upright: ["new beginnings", "trust"], reversed: ["recklessness", "naivety"] },
  magician: { upright: ["manifestation", "willpower"], reversed: ["manipulation", "unused potential"] },
  high_priestess: { upright: ["intuition", "inner knowing"], reversed: ["secrets", "blocked intuition"] },
  empress: { upright: ["abundance", "nurturing"], reversed: ["creative block", "dependence"] },
  emperor: { upright: ["structure", "authority"], reversed: ["control", "rigidity"] },
  hierophant: { upright: ["tradition", "teaching"], reversed: ["nonconformity", "questioning tradition"] },
  lovers: { upright: ["alignment", "choice"], reversed: ["misalignment", "disharmony"] },
  chariot: { upright: ["determination", "victory"], reversed: ["lack of control", "scattered direction"] },
  strength: { upright: ["courage", "compassion"], reversed: ["self-doubt", "inner weakness"] },
  hermit: { upright: ["introspection", "inner guidance"], reversed: ["isolation", "withdrawal"] },
  wheel_of_fortune: { upright: ["turning point", "cycles"], reversed: ["resistance to change", "setbacks"] },
  justice: { upright: ["fairness", "accountability"], reversed: ["bias", "dishonesty"] },
  hanged_man: { upright: ["pause", "new perspective"], reversed: ["stalling", "resistance"] },
  death: { upright: ["transformation", "ending"], reversed: ["resisting change", "stagnation"] },
  temperance: { upright: ["balance", "moderation"], reversed: ["imbalance", "excess"] },
  devil: { upright: ["attachment", "shadow"], reversed: ["release", "reclaiming power"] },
  tower: { upright: ["upheaval", "revelation"], reversed: ["avoiding change", "delayed disruption"] },
  star: { upright: ["hope", "renewal"], reversed: ["discouragement", "loss of faith"] },
  moon: { upright: ["illusion", "uncertainty"], reversed: ["clarity", "revealed truth"] },
  sun: { upright: ["joy", "success"], reversed: ["temporary cloudiness", "delayed joy"] },
  judgement: { upright: ["awakening", "renewal"], reversed: ["self-doubt", "avoidance"] },
  world: { upright: ["completion", "integration"], reversed: ["unfinished business", "lack of closure"] },
  ace_of_wands: { upright: ["inspiration", "creative spark"], reversed: ["delays", "blocked passion"] },
  two_of_wands: { upright: ["planning", "future vision"], reversed: ["fear of change", "small thinking"] },
  three_of_wands: { upright: ["expansion", "foresight"], reversed: ["delays", "limited growth"] },
  four_of_wands: { upright: ["celebration", "homecoming"], reversed: ["instability", "private celebration"] },
  five_of_wands: { upright: ["competition", "conflict"], reversed: ["conflict avoidance", "resolution"] },
  six_of_wands: { upright: ["recognition", "victory"], reversed: ["self-doubt", "lack of recognition"] },
  seven_of_wands: { upright: ["defense", "perseverance"], reversed: ["overwhelm", "giving up"] },
  eight_of_wands: { upright: ["speed", "movement"], reversed: ["delays", "miscommunication"] },
  nine_of_wands: { upright: ["resilience", "boundaries"], reversed: ["exhaustion", "paranoia"] },
  ten_of_wands: { upright: ["burden", "responsibility"], reversed: ["release", "delegation"] },
  page_of_wands: { upright: ["enthusiasm", "exploration"], reversed: ["hesitation", "unfocused energy"] },
  knight_of_wands: { upright: ["action", "adventure"], reversed: ["impulsiveness", "scattered energy"] },
  queen_of_wands: { upright: ["confidence", "vibrancy"], reversed: ["insecurity", "jealousy"] },
  king_of_wands: { upright: ["leadership", "vision"], reversed: ["impulsiveness", "domineering"] },
  ace_of_cups: { upright: ["new love", "emotional opening"], reversed: ["blocked emotion", "self-love needed"] },
  two_of_cups: { upright: ["partnership", "mutual attraction"], reversed: ["imbalance", "disconnection"] },
  three_of_cups: { upright: ["friendship", "community"], reversed: ["overindulgence", "exclusion"] },
  four_of_cups: { upright: ["apathy", "contemplation"], reversed: ["new awareness", "re-engagement"] },
  five_of_cups: { upright: ["grief", "disappointment"], reversed: ["acceptance", "moving on"] },
  six_of_cups: { upright: ["nostalgia", "kindness"], reversed: ["living in the past", "maturity"] },
  seven_of_cups: { upright: ["choices", "fantasy"], reversed: ["clarity", "focused choice"] },
  eight_of_cups: { upright: ["walking away", "seeking meaning"], reversed: ["fear of leaving", "aimless drifting"] },
  nine_of_cups: { upright: ["contentment", "wish fulfillment"], reversed: ["inner dissatisfaction", "smugness"] },
  ten_of_cups: { upright: ["harmony", "family joy"], reversed: ["disconnection", "unrealistic expectations"] },
  page_of_cups: { upright: ["creative message", "emotional openness"], reversed: ["emotional immaturity", "creative block"] },
  knight_of_cups: { upright: ["romance", "idealism"], reversed: ["moodiness", "unrealistic romance"] },
  queen_of_cups: { upright: ["compassion", "emotional wisdom"], reversed: ["emotional overwhelm", "poor boundaries"] },
  king_of_cups: { upright: ["emotional balance", "wise counsel"], reversed: ["emotional manipulation", "repression"] },
  ace_of_swords: { upright: ["clarity", "breakthrough"], reversed: ["confusion", "miscommunication"] },
  two_of_swords: { upright: ["stalemate", "difficult choice"], reversed: ["indecision", "information overload"] },
  three_of_swords: { upright: ["heartbreak", "truth"], reversed: ["healing", "forgiveness"] },
  four_of_swords: { upright: ["rest", "recovery"], reversed: ["burnout", "restlessness"] },
  five_of_swords: { upright: ["conflict", "hollow victory"], reversed: ["reconciliation", "resentment"] },
  six_of_swords: { upright: ["transition", "moving on"], reversed: ["resistance to transition", "emotional baggage"] },
  seven_of_swords: { upright: ["strategy", "deception"], reversed: ["confession", "self-deception"] },
  eight_of_swords: { upright: ["restriction", "limiting beliefs"], reversed: ["release", "new perspective"] },
  nine_of_swords: { upright: ["anxiety", "nightmares"], reversed: ["recovery", "hope"] },
  ten_of_swords: { upright: ["painful ending", "collapse"], reversed: ["survival", "recovery"] },
  page_of_swords: { upright: ["curiosity", "watchfulness"], reversed: ["gossip", "all talk"] },
  knight_of_swords: { upright: ["ambition", "direct action"], reversed: ["recklessness", "haste"] },
  queen_of_swords: { upright: ["clear boundaries", "independence"], reversed: ["coldness", "bitterness"] },
  king_of_swords: { upright: ["mental clarity", "authority"], reversed: ["abuse of power", "manipulative logic"] },
  ace_of_pentacles: { upright: ["opportunity", "prosperity"], reversed: ["missed opportunity", "poor planning"] },
  two_of_pentacles: { upright: ["balance", "adaptability"], reversed: ["overcommitment", "disorganization"] },
  three_of_pentacles: { upright: ["teamwork", "craftsmanship"], reversed: ["poor collaboration", "low standards"] },
  four_of_pentacles: { upright: ["security", "control"], reversed: ["scarcity mindset", "letting go"] },
  five_of_pentacles: { upright: ["hardship", "exclusion"], reversed: ["recovery", "help received"] },
  six_of_pentacles: { upright: ["generosity", "fair exchange"], reversed: ["strings attached", "imbalance"] },
  seven_of_pentacles: { upright: ["patience", "assessment"], reversed: ["impatience", "wasted effort"] },
  eight_of_pentacles: { upright: ["skill building", "dedication"], reversed: ["perfectionism", "lack of focus"] },
  nine_of_pentacles: { upright: ["self-sufficiency", "luxury"], reversed: ["overdependence", "self-worth issues"] },
  ten_of_pentacles: { upright: ["legacy", "family wealth"], reversed: ["family conflict", "unstable legacy"] },
  page_of_pentacles: { upright: ["study", "practical opportunity"], reversed: ["procrastination", "lack of progress"] },
  knight_of_pentacles: { upright: ["reliability", "steady progress"], reversed: ["stagnation", "stubbornness"] },
  queen_of_pentacles: { upright: ["nurturing abundance", "practical care"], reversed: ["work-life imbalance", "self-neglect"] },
  king_of_pentacles: { upright: ["prosperity", "practical leadership"], reversed: ["greed", "materialism"] },
};

export const BANNED_LEGACY_KEYWORDS_BY_CARD: Array<{
  id: string;
  keyword: string;
}> = [
  { id: "star", keyword: "privation" },
  { id: "wheel_of_fortune", keyword: "increase" },
  { id: "five_of_pentacles", keyword: "lovers" },
  { id: "five_of_wands", keyword: "mimic warfare" },
  { id: "three_of_pentacles", keyword: "metier" },
  { id: "eight_of_swords", keyword: "durance" },
  { id: "five_of_swords", keyword: "obsequies" },
];
